export enum MediaActions {
  NONE = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NONE',
  PLAY = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PLAY',
  PAUSE = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PAUSE',
  STOP = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_STOP',
  RESTART = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_RESTART',
  NEXT = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NEXT',
  PREVIOUS = 'OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PREVIOUS',
}
